:concurrency: 1
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
development:
  :concurrency: 2
production:
  :concurrency: 10
:queues:
  - development_ocr_queue
  - production_ocr_queue

tasks: &tasks
  NotifierJob:
    every: ["2s"]
    queue: notifier
    description: 'Send pending notifications'

:schedule:
  <<: *tasks
